networks:
  ejbca-frontend:
    driver: bridge
  ejbca-backend:
    driver: bridge
services:
  db:
    image: "library/mariadb:latest"
    #user: ${MYSQL_UID}:${MYSQL_GID}"
    networks:
      - ejbca-backend
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${EJBCA_DB_PATH}:/var/lib/mysql:rw
  node1:
    hostname: ejbca-node1
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - db
    networks:
      - ejbca-frontend
      - ejbca-backend
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://db:3306/ejbca?characterEncoding=UTF-8
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=simple
      - HTTPSERVER_HOSTNAME=${EJBCA_HTTPSERVER_HOSTNAME}
    ports:
      - "8080:8080"
      - "9443:8443"
