networks:
  ejbca-frontend:
    driver: bridge
  ejbca-backend:
    driver: bridge
services:
  db:
    image: "library/mariadb:latest"
    #user: ${MYSQL_UID}:${MYSQL_GID}"
    networks:
      - ejbca-backend
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${EJBCA_DB_PATH}:/var/lib/mysql:rw
  node1:
    hostname: ejbca-node1
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - db
    networks:
      - ejbca-frontend
      - ejbca-backend
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://db:3306/ejbca?characterEncoding=UTF-8
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=simple
      - HTTPSERVER_HOSTNAME=${EJBCA_HTTPSERVER_HOSTNAME} # TODO: need to manually update httpserver.privhttps=8443, httpserver.pubhttps=9443 and httpserver.external.privhttps=9443
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/opt/keyfactor/secrets/external/tls/ts/truststore.jks -Djavax.net.ssl.trustStorePassword=${EJBCA_TRUSTSTORE_PASSWD} -Xms128m -Xmx2464m -Xss256k -XX:MetaspaceSize=160m -XX:MaxMetaspaceSize=1232m -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:/dev/random -Dcontainer.database.name=mysql -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
    volumes:
      - ${EJBCA_TRUSTSTORE_PATH}:/opt/keyfactor/secrets/external/tls/ts/truststore.jks
      - ${EJBCA_TRUSTSTORE_PASSWD_PATH}:/opt/keyfactor/secrets/external/tls/ts/truststore.storepasswd 
      - ${EJBCA_KEYSTORE_PATH}:/mnt/external/secrets/tls/ks/server.jks
      - ${EJBCA_KEYSTORE_PASSWD_PATH}:/mnt/external/secrets/tls/ks/server.password
    ports:
      - "8080:8080"
      - "9443:8443"
