networks:
  access-bridge:
    driver: bridge
  application-bridge:
    driver: bridge
services:
  ejbca-db:
    image: "library/mariadb:latest"
    networks:
      - ejbca-backend
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${EJBCA_DB_PATH}:/var/lib/mysql:rw
  ejbca-node1:
    hostname: ejbca-node1
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - ejbca-db
    networks:
      - ejbca-frontend
      - ejbca-backend
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://ejbca-db:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=simple
    ports:
      - "80:8080"
      - "443:8443"
